// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB
{
    public partial class Notities
    {
        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string Notitie { get; set; }
        public string AssigningUserId { get; set; }
        [StringLength(40)]
        public string AssigningUserName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Timestamp { get; set; }
        [StringLength(25)]
        public string Category { get; set; }
        public bool? Processed { get; set; }
        [StringLength(15)]
        public string Phone { get; set; }
        [StringLength(40)]
        public string PersonToCallName { get; set; }
        public string AssignedUserId { get; set; }
        [StringLength(40)]
        public string AssignedUserName { get; set; }
    }
}